#include "../headers/hashmap.h"
#include <stdio.h>
#include <assert.h>

int main(){
    hashmap *test = new_hashmap(20 , NULL , false);
    assert(test != NULL);

    //generated by chat gibbity
    char *rand_str[] = {"apple", "banana", "carrot", "elephant", "giraffe", "happiness"};

    printf("testing the adding function...");
    for(int i = 0 ; i < 6 ; i++){
        datastruct_err err = hashmap_add_entry(rand_str[i] , rand_str[i] , strnlen_s(rand_str[i] , SSIZE_MAX) + 1 , NULL , test);
        assert(err == Success);
    }
    printf("success\n");

    printf("testing the lookup function...");
    entry *entry_ptr = NULL;
    void *obj_ptr = NULL;
    for(int i = 0 ; i < 6 ; i++){
        entry_ptr = hashmap_lookup_entry(rand_str[i] , test);
        assert(entry_ptr != NULL);

        obj_ptr = hashmap_get_obj_ptr(entry_ptr);
        assert(strcmp((char *)obj_ptr , rand_str[i]) == 0);
    }
    printf("success\n");

    printf("testing the deleting function...");
    datastruct_err err = hashmap_delete_entry(rand_str[0] , test);
    assert(err == Success);
    entry_ptr = hashmap_lookup_entry(rand_str[0] , test);
    assert(entry_ptr == NULL);
    printf("success\n");

    destroy_hashmap(test);
    
    return 0;
}